spring:
  profiles:
    include: [ jwt, oauth ]

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug