spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

